import dotenv from 'dotenv';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: join(__dirname, '../.env') });

import { admin } from './middleware/auth.js';

const db = admin.firestore();

const products = [
  // Classical Medicines
  {
    name: 'Triphala Churna',
    description: 'A traditional Ayurvedic formulation for digestive health and rejuvenation.',
    price: 150,
    stock: 120,
    imageUrl: 'https://images.unsplash.com/photo-1611162458324-aae1eb4129a4?w=500&auto=format&fit=crop&q=60',
    category: 'Classical Medicines',
    brand: 'Dabur',
    prescription: false,
    rating: 4.8,
    discount: 5,
  },
  {
    name: 'Dashamoolarishta',
    description: 'A liquid Ayurveda medicine used in the treatment of post-delivery care, joint pain, and immunity.',
    price: 240,
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1607527633633-5c25091ffba9?w=500&auto=format&fit=crop&q=60',
    category: 'Classical Medicines',
    brand: 'Baidyanath',
    prescription: false,
    rating: 4.5,
  },
  {
    name: 'Chyawanprash',
    description: 'A comprehensive herbal tonic with amla and herbs to supercharge immunity.',
    price: 320,
    stock: 200,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=60',
    category: 'Classical Medicines',
    brand: 'Patanjali',
    prescription: false,
    rating: 4.9,
    discount: 10,
  },
  {
    name: 'Ashwagandharishta',
    description: 'Useful for treating fatigue, anxiety, and general debility.',
    price: 180,
    stock: 80,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=60',
    category: 'Classical Medicines',
    brand: 'AyurSutra Originals',
    prescription: false,
    rating: 4.6,
  },
  {
    name: 'Brahmi Vati',
    description: 'Enhances memory, relieves stress and calms the nervous system.',
    price: 210,
    stock: 65,
    imageUrl: 'https://images.unsplash.com/photo-1629857997380-f65c1926fec9?w=500&auto=format&fit=crop&q=60',
    category: 'Classical Medicines',
    brand: 'Himalaya',
    prescription: true,
    rating: 4.4,
  },
  {
    name: 'Sitopaladi Churna',
    description: 'Effective Ayurvedic formulation for respiratory health and cough relief.',
    price: 130,
    stock: 90,
    imageUrl: 'https://images.unsplash.com/photo-1611162458324-aae1eb4129a4?w=500&auto=format&fit=crop&q=60',
    category: 'Classical Medicines',
    brand: 'Dhootapapeshwar',
    prescription: false,
    rating: 4.7,
  },

  // Proprietary Formulations
  {
    name: 'Ayush Kwath',
    description: 'A comprehensive blend of herbs that acts as an immunity booster.',
    price: 99,
    stock: 150,
    imageUrl: 'https://images.unsplash.com/photo-1563200922-26db12903110?w=500&auto=format&fit=crop&q=60',
    category: 'Proprietary Formulations',
    brand: 'Ayush',
    prescription: false,
    rating: 4.2,
  },
  {
    name: 'Liver Protect Syrup',
    description: 'Premium formulation containing Kalmegh and Punarnava for liver detox.',
    price: 299,
    stock: 45,
    imageUrl: 'https://images.unsplash.com/photo-1607527633633-5c25091ffba9?w=500&auto=format&fit=crop&q=60',
    category: 'Proprietary Formulations',
    brand: 'AyurSutra Originals',
    prescription: true,
    rating: 4.8,
    discount: 15,
  },
  {
    name: 'Joint Pain Relief Tablets',
    description: 'Shallaki and Guggulu extracts for immediate joint comfort.',
    price: 450,
    stock: 80,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=60',
    category: 'Proprietary Formulations',
    brand: 'Himalaya',
    prescription: false,
    rating: 4.5,
  },
  {
    name: 'Digestion Plus Drops',
    description: 'Quick-acting drops for instant relief from bloating and acidity.',
    price: 120,
    stock: 300,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=60',
    category: 'Proprietary Formulations',
    brand: 'Zandu',
    prescription: false,
    rating: 4.6,
  },
  {
    name: 'Sugar Balance Capsules',
    description: 'Formulated with Jamun, Karela, and Gurmar to regulate blood sugar.',
    price: 550,
    stock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1629857997380-f65c1926fec9?w=500&auto=format&fit=crop&q=60',
    category: 'Proprietary Formulations',
    brand: 'Sri Sri Tattva',
    prescription: true,
    rating: 4.7,
  },
  {
    name: 'Sleep Easy Tablets',
    description: 'Non-habit forming Tagar and Jatamansi blend for deep sleep.',
    price: 350,
    stock: 100,
    imageUrl: 'https://images.unsplash.com/photo-1611162458324-aae1eb4129a4?w=500&auto=format&fit=crop&q=60',
    category: 'Proprietary Formulations',
    brand: 'AyurSutra Originals',
    prescription: false,
    rating: 4.9,
    discount: 20,
  },

  // Oils & Ghritas
  {
    name: 'Mahanarayan Taila',
    description: 'Ancient massage oil for severe joint issues, arthritis, and muscle stiffness.',
    price: 380,
    stock: 90,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661601777265-d6023d8cbbc0?w=500&auto=format&fit=crop&q=60',
    category: 'Oils & Ghritas',
    brand: 'Baidyanath',
    prescription: false,
    rating: 4.8,
  },
  {
    name: 'Anu Taila',
    description: 'Nasal drops for respiratory health and clearing sinus congestion.',
    price: 150,
    stock: 110,
    imageUrl: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=500&auto=format&fit=crop&q=60',
    category: 'Oils & Ghritas',
    brand: 'Kottakkal',
    prescription: false,
    rating: 4.6,
  },
  {
    name: 'Kumkumadi Tailam',
    description: 'Luxury saffron oil for radiant, glowing skin and treating blemishes.',
    price: 1200,
    stock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&auto=format&fit=crop&q=60',
    category: 'Oils & Ghritas',
    brand: 'Kama Ayurveda',
    prescription: false,
    rating: 4.9,
    discount: 5,
  },
  {
    name: 'Brahmi Ghrita',
    description: 'Medicated ghee to enhance cognitive functions, memory, and speech.',
    price: 450,
    stock: 25,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661601777265-d6023d8cbbc0?w=500&auto=format&fit=crop&q=60',
    category: 'Oils & Ghritas',
    brand: 'Patanjali',
    prescription: true,
    rating: 4.7,
  },
  {
    name: 'Kshirabala Taila',
    description: 'Nourishing oil for Vata disorders and severe nerve-related pains.',
    price: 320,
    stock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=500&auto=format&fit=crop&q=60',
    category: 'Oils & Ghritas',
    brand: 'Arya Vaidya Sala',
    prescription: false,
    rating: 4.6,
  },
  {
    name: 'Bhringraj Hair Oil',
    description: 'Intensive hair treatment oil for hair fall, premature graying, and scalp health.',
    price: 290,
    stock: 200,
    imageUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&auto=format&fit=crop&q=60',
    category: 'Oils & Ghritas',
    brand: 'AyurSutra Originals',
    prescription: false,
    rating: 4.8,
    discount: 10,
  },

  // Herbal Supplements
  {
    name: 'Organic Ashwagandha Extract',
    description: 'Potent adaptogen for stress relief, energy, and muscle recovery.',
    price: 599,
    stock: 180,
    imageUrl: 'https://images.unsplash.com/photo-1611162458324-aae1eb4129a4?w=500&auto=format&fit=crop&q=60',
    category: 'Herbal Supplements',
    brand: 'Organic India',
    prescription: false,
    rating: 4.9,
  },
  {
    name: 'Pure Shilajit Resin',
    description: 'Himalayan Shilajit for unmatched strength, stamina, and vitality.',
    price: 1499,
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1607527633633-5c25091ffba9?w=500&auto=format&fit=crop&q=60',
    category: 'Herbal Supplements',
    brand: 'Kapiva',
    prescription: false,
    rating: 4.7,
    discount: 15,
  },
  {
    name: 'Organic Turmeric Curcumin',
    description: 'High-absorption curcumin with black pepper for anti-inflammatory support.',
    price: 499,
    stock: 120,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=60',
    category: 'Herbal Supplements',
    brand: 'Organic India',
    prescription: false,
    rating: 4.8,
  },
  {
    name: 'Neem Capsules',
    description: 'Natural blood purifier for glowing skin and robust immunity.',
    price: 250,
    stock: 80,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=60',
    category: 'Herbal Supplements',
    brand: 'Himalaya',
    prescription: false,
    rating: 4.6,
  },
  {
    name: 'Moringa Powder',
    description: 'Nutrient-dense superfood powder rich in vitamins and minerals.',
    price: 350,
    stock: 65,
    imageUrl: 'https://images.unsplash.com/photo-1629857997380-f65c1926fec9?w=500&auto=format&fit=crop&q=60',
    category: 'Herbal Supplements',
    brand: 'AyurSutra Originals',
    prescription: false,
    rating: 4.5,
  },
  {
    name: 'Shatavari Extract',
    description: 'Female reproductive tonic to support hormonal balance and vitality.',
    price: 450,
    stock: 90,
    imageUrl: 'https://images.unsplash.com/photo-1611162458324-aae1eb4129a4?w=500&auto=format&fit=crop&q=60',
    category: 'Herbal Supplements',
    brand: 'Jiva Ayurveda',
    prescription: false,
    rating: 4.8,
  },

  // Personal Care
  {
    name: 'Sandalwood Soap',
    description: 'Pure Mysore sandalwood soap for a soothing, fragrant bathing experience.',
    price: 85,
    stock: 400,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661601777265-d6023d8cbbc0?w=500&auto=format&fit=crop&q=60',
    category: 'Personal Care',
    brand: 'Mysore Sandal',
    prescription: false,
    rating: 4.7,
  },
  {
    name: 'Neem & Aloe Face Wash',
    description: 'Antibacterial face wash to prevent pimples and keep skin hydrated.',
    price: 150,
    stock: 250,
    imageUrl: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=500&auto=format&fit=crop&q=60',
    category: 'Personal Care',
    brand: 'Himalaya',
    prescription: false,
    rating: 4.6,
  },
  {
    name: 'Ayurvedic Toothpaste',
    description: 'Formulated with clove, neem, and babool for strong teeth and gums.',
    price: 95,
    stock: 300,
    imageUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&auto=format&fit=crop&q=60',
    category: 'Personal Care',
    brand: 'Dabur Red',
    prescription: false,
    rating: 4.8,
    discount: 5,
  },
  {
    name: 'Shikakai Shampoo',
    description: 'Natural foaming shampoo with Shikakai and Amla to prevent hair fall.',
    price: 220,
    stock: 140,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1661601777265-d6023d8cbbc0?w=500&auto=format&fit=crop&q=60',
    category: 'Personal Care',
    brand: 'Khadi Natural',
    prescription: false,
    rating: 4.5,
  },
  {
    name: 'Rose Water Mist',
    description: '100% pure distilled rose water for instant skin refreshing.',
    price: 295,
    stock: 180,
    imageUrl: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=500&auto=format&fit=crop&q=60',
    category: 'Personal Care',
    brand: 'Kama Ayurveda',
    prescription: false,
    rating: 4.9,
  },
  {
    name: 'Turmeric Body Lotion',
    description: 'Nourishing lotion with turmeric extract for glowing, soft skin.',
    price: 310,
    stock: 120,
    imageUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&auto=format&fit=crop&q=60',
    category: 'Personal Care',
    brand: 'Vicco',
    prescription: false,
    rating: 4.6,
  },

  // Immunity Boosters
  {
    name: 'Giloy Ghanvati',
    description: 'Powerful antipyretic and immunity modulator herbal tablets.',
    price: 110,
    stock: 200,
    imageUrl: 'https://images.unsplash.com/photo-1611162458324-aae1eb4129a4?w=500&auto=format&fit=crop&q=60',
    category: 'Immunity Boosters',
    brand: 'Patanjali',
    prescription: false,
    rating: 4.7,
  },
  {
    name: 'Amla Juice',
    description: 'Pure cold-pressed Indian Gooseberry juice loaded with Vitamin C.',
    price: 220,
    stock: 150,
    imageUrl: 'https://images.unsplash.com/photo-1607527633633-5c25091ffba9?w=500&auto=format&fit=crop&q=60',
    category: 'Immunity Boosters',
    brand: 'Kapiva',
    prescription: false,
    rating: 4.8,
    discount: 10,
  },
  {
    name: 'Tulsi Drops',
    description: 'Extract of 5 sacred Tulsi varieties. Add to water for daily immunity.',
    price: 195,
    stock: 280,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=60',
    category: 'Immunity Boosters',
    brand: 'Dabur',
    prescription: false,
    rating: 4.6,
  },
  {
    name: 'Curcumin Drops',
    description: 'Liquid turmeric extract for high bioavailability and immune defense.',
    price: 340,
    stock: 90,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=60',
    category: 'Immunity Boosters',
    brand: 'AyurSutra Originals',
    prescription: false,
    rating: 4.9,
  },
  {
    name: 'Swarna Bhasma (Gold trace)',
    description: 'Rare Ayurvedic gold ash preparation for extreme immune enhancement.',
    price: 2500,
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1629857997380-f65c1926fec9?w=500&auto=format&fit=crop&q=60',
    category: 'Immunity Boosters',
    brand: 'Dhootapapeshwar',
    prescription: true,
    rating: 4.9,
  },
  {
    name: 'Organic Wild Honey',
    description: 'Unprocessed forest honey that acts as an anupana (carrier) for herbs.',
    price: 450,
    stock: 160,
    imageUrl: 'https://images.unsplash.com/photo-1611162458324-aae1eb4129a4?w=500&auto=format&fit=crop&q=60',
    category: 'Immunity Boosters',
    brand: 'Vedic Roots',
    prescription: false,
    rating: 4.8,
  }
];

async function seed() {
  console.log('Starting dummy product seed...');
  let count = 0;
  for (const product of products) {
    try {
      await db.collection('products').add({
        ...product,
        createdAt: new Date().toISOString()
      });
      count++;
    } catch (err) {
      console.error(`Failed to seed ${product.name}:`, err);
    }
  }
  console.log(`✅ Successfully seeded ${count} products.`);
  process.exit(0);
}

seed();
